### Get Headers
GET  http://localhost:3000/api/auth/headers

### Sign Up
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "1@1.com",
    "username": "1",
    "password": "1",
    "firstName": "1",
    "lastName": "1"
}

### Sign In
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "identifier": "1@1.com",
    "password": "1"
}

### Get Me
GET  http://localhost:3000/api/auth/me
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTY5NzkwMDA0NywiZXhwIjoxNjk3OTg2NDQ3fQ.ZhT4YahOKXU4gM1z8O7vS5bktMoSkBqrBxlz2moB_7M"
}

### test
GET http://localhost:3000/api/auth/testGuard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImlhdCI6MTY5NzkwMDI5MSwiZXhwIjoxNjk3OTg2NjkxfQ.hOeTRlm6Iv6DLux787lsonb6ClRP0eNUu0l7hNRi8w4