### Sign Up
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email": "gvantsa@pestvenidze.com",
    "username": "gvantsapestvenidze",
    "password": "gvantsa",
    "firstName": "gvantsa",
    "lastName": "pestvenidze"
}

### Sign In
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "identifier": "elenepestvenidze",
    "password": "enene"
}

### Get Me
GET  http://localhost:3000/api/auth/me
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjkzNDYzMjIzLCJleHAiOjE2OTM1NDk2MjN9.T0sh598wj4K9HRj0P5F7vwiA-TdWX21nNaqVEEecglw"
}


### Get User by id
GET  http://localhost:3000/api/users/1

### Get User by username
GET  http://localhost:3000/api/users/mariampestvenidze


### Get User by email
GET  http://localhost:3000/api/users/mariam@pestvenidze.com

### Get Headers
GET  http://localhost:3000/api/auth/headers