### Sign Up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "tatia@pestvenidze.com",
    "username": "tatiapestvenidze",
    "password": "tatuli",
    "firstName": "tatia",
    "lastName": "pestvenidze"
}

### Sign In
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "identifier": "tatiapestvenidze",
    "password": "tatuli"
}